
   const data = [
        {
            "league_id": "25",
            "season_id": "2",
            "name": "Liverpool",
            "rank": "1",
            "points": "21",
            "matches": "7",
            "goal_diff": "13",
            "goals_scored": "18",
            "goals_conceded": "5",
            "lost": "0",
            "drawn": "0",
            "won": "7",
            "team_id": "7",
            "competition_id": "2"
        },
        {
            "league_id": "25",
            "season_id": "2",
            "name": "Manchester City",
            "rank": "2",
            "points": "16",
            "matches": "7",
            "goal_diff": "20",
            "goals_scored": "27",
            "goals_conceded": "7",
            "lost": "1",
            "drawn": "1",
            "won": "5",
            "team_id": "12",
            "competition_id": "2"
        },
        {
            "league_id": "25",
            "season_id": "2",
            "name": "Leicester City",
            "rank": "3",
            "points": "14",
            "matches": "7",
            "goal_diff": "8",
            "goals_scored": "13",
            "goals_conceded": "5",
            "lost": "1",
            "drawn": "2",
            "won": "4",
            "team_id": "6",
            "competition_id": "2"
        },
        {
            "league_id": "25",
            "season_id": "2",
            "name": "Arsenal",
            "rank": "4",
            "points": "12",
            "matches": "7",
            "goal_diff": "1",
            "goals_scored": "12",
            "goals_conceded": "11",
            "lost": "1",
            "drawn": "3",
            "won": "3",
            "team_id": "18",
            "competition_id": "2"
        },
        {
            "league_id": "25",
            "season_id": "2",
            "name": "West Ham United",
            "rank": "5",
            "points": "12",
            "matches": "7",
            "goal_diff": "1",
            "goals_scored": "10",
            "goals_conceded": "9",
            "lost": "1",
            "drawn": "3",
            "won": "3",
            "team_id": "14",
            "competition_id": "2"
        },
        {
            "league_id": "25",
            "season_id": "2",
            "name": "Tottenham Hotspur",
            "rank": "6",
            "points": "11",
            "matches": "7",
            "goal_diff": "5",
            "goals_scored": "14",
            "goals_conceded": "9",
            "lost": "2",
            "drawn": "2",
            "won": "3",
            "team_id": "15",
            "competition_id": "2"
        },
        {
            "league_id": "25",
            "season_id": "2",
            "name": "Chelsea",
            "rank": "7",
            "points": "11",
            "matches": "7",
            "goal_diff": "1",
            "goals_scored": "14",
            "goals_conceded": "13",
            "lost": "2",
            "drawn": "2",
            "won": "3",
            "team_id": "17",
            "competition_id": "2"
        },
        {
            "league_id": "25",
            "season_id": "2",
            "name": "AFC Bournemouth",
            "rank": "8",
            "points": "11",
            "matches": "7",
            "goal_diff": "1",
            "goals_scored": "13",
            "goals_conceded": "12",
            "lost": "2",
            "drawn": "2",
            "won": "3",
            "team_id": "1",
            "competition_id": "2"
        },
        {
            "league_id": "25",
            "season_id": "2",
            "name": "Crystal Palace",
            "rank": "9",
            "points": "11",
            "matches": "7",
            "goal_diff": "-1",
            "goals_scored": "6",
            "goals_conceded": "7",
            "lost": "2",
            "drawn": "2",
            "won": "3",
            "team_id": "3",
            "competition_id": "2"
        },
        {
            "league_id": "25",
            "season_id": "2",
            "name": "Manchester United",
            "rank": "10",
            "points": "9",
            "matches": "7",
            "goal_diff": "2",
            "goals_scored": "9",
            "goals_conceded": "7",
            "lost": "2",
            "drawn": "3",
            "won": "2",
            "team_id": "19",
            "competition_id": "2"
        },
        {
            "league_id": "25",
            "season_id": "2",
            "name": "Burnley",
            "rank": "11",
            "points": "9",
            "matches": "7",
            "goal_diff": "1",
            "goals_scored": "10",
            "goals_conceded": "9",
            "lost": "2",
            "drawn": "3",
            "won": "2",
            "team_id": "8",
            "competition_id": "2"
        },
        {
            "league_id": "25",
            "season_id": "2",
            "name": "Sheffield United",
            "rank": "12",
            "points": "8",
            "matches": "7",
            "goal_diff": "0",
            "goals_scored": "7",
            "goals_conceded": "7",
            "lost": "3",
            "drawn": "2",
            "won": "2",
            "team_id": "281",
            "competition_id": "2"
        },
        {
            "league_id": "25",
            "season_id": "2",
            "name": "Wolverhampton Wanderers",
            "rank": "13",
            "points": "7",
            "matches": "7",
            "goal_diff": "-2",
            "goals_scored": "9",
            "goals_conceded": "11",
            "lost": "2",
            "drawn": "4",
            "won": "1",
            "team_id": "497",
            "competition_id": "2"
        },
        {
            "league_id": "25",
            "season_id": "2",
            "name": "Southampton",
            "rank": "14",
            "points": "7",
            "matches": "7",
            "goal_diff": "-4",
            "goals_scored": "7",
            "goals_conceded": "11",
            "lost": "4",
            "drawn": "1",
            "won": "2",
            "team_id": "4",
            "competition_id": "2"
        },
        {
            "league_id": "25",
            "season_id": "2",
            "name": "Everton",
            "rank": "15",
            "points": "7",
            "matches": "7",
            "goal_diff": "-6",
            "goals_scored": "6",
            "goals_conceded": "12",
            "lost": "4",
            "drawn": "1",
            "won": "2",
            "team_id": "20",
            "competition_id": "2"
        },
        {
            "league_id": "25",
            "season_id": "2",
            "name": "Brighton & Hove Albion",
            "rank": "16",
            "points": "6",
            "matches": "7",
            "goal_diff": "-5",
            "goals_scored": "5",
            "goals_conceded": "10",
            "lost": "3",
            "drawn": "3",
            "won": "1",
            "team_id": "2",
            "competition_id": "2"
        },
        {
            "league_id": "25",
            "season_id": "2",
            "name": "Norwich City",
            "rank": "17",
            "points": "6",
            "matches": "7",
            "goal_diff": "-7",
            "goals_scored": "9",
            "goals_conceded": "16",
            "lost": "5",
            "drawn": "0",
            "won": "2",
            "team_id": "492",
            "competition_id": "2"
        },
        {
            "league_id": "25",
            "season_id": "2",
            "name": "Aston Villa",
            "rank": "18",
            "points": "5",
            "matches": "7",
            "goal_diff": "-3",
            "goals_scored": "8",
            "goals_conceded": "11",
            "lost": "4",
            "drawn": "2",
            "won": "1",
            "team_id": "495",
            "competition_id": "2"
        },
        {
            "league_id": "25",
            "season_id": "2",
            "name": "Newcastle United",
            "rank": "19",
            "points": "5",
            "matches": "7",
            "goal_diff": "-9",
            "goals_scored": "4",
            "goals_conceded": "13",
            "lost": "4",
            "drawn": "2",
            "won": "1",
            "team_id": "9",
            "competition_id": "2"
        },
        {
            "league_id": "25",
            "season_id": "2",
            "name": "Watford",
            "rank": "20",
            "points": "2",
            "matches": "7",
            "goal_diff": "-16",
            "goals_scored": "4",
            "goals_conceded": "20",
            "lost": "5",
            "drawn": "2",
            "won": "0",
            "team_id": "11",
            "competition_id": "2"
        }
    ]



export default data
